### ISSUE TITLE
preserving comments and indent

### ISSUE THREAD

**Issue by JohannesBuchner** [FelixTheC/docstring_generator#9]
Hi,

This looks like a  useful tool. I wish I had come across it earlier!

I tried to write a similar tool for numpy-style docstrings today.

Initially, I was also working with ast. I have done some work with it for pystrict3 (https://github.com/JohannesBuchner/pystrict3), a static python code analyser.

Unfortunately, I noticed that code comments and formatting is discarded in ast roundtrips.
Subsequently, through the https://greentreesnakes.readthedocs.io/en/latest/ documentation, I became aware of RedBaron https://redbaron.readthedocs.io/en/latest/ which allows surgically altering only specific portions of the syntax tree, keeping formatting and comments in place.

I distribute the tool I wrote today, gendocstr.py with pystrict3 (available on pypi), and documented it here: https://github.com/JohannesBuchner/pystrict3#gendocstrpy-tool

There are still some problems with RedBaron, the indent comes out weird sometimes: https://github.com/PyCQA/redbaron/issues/219 

In any case, my use case was/is slightly different, as I want to be able to rewrite the file repeatedly, and not always rely on type annotations.

Cheers,
Johannes

**Comment by FelixTheC** [comment]
Hi thanks for sharing this with me. If you want we can also collaborate on such a tool.

Cheers,
Felix
